DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(kap@lv%9gg@5nv-28(ry3f@*5j(b_1t@)d!nq1)$gpt^xka*g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Permitir acesso via Nginx (localhost) e direto (porta 8000)
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',  # CORS support

    # Apps locais
    'backend.core',  # Core app com signals
    'backend.pessoas',
    'backend.campanhas',
    'backend.doacoes',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS - deve vir antes do CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'backend.core.middleware.AutoClearCorruptedCacheMiddleware',  # Auto-limpeza de cache corrompido
]

ROOT_URLCONF = 'backend.core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os
import dj_database_url

# Usar DATABASE_URL se disponível (para CI/CD), senão usar configuração padrão
DATABASES = {
    "default": dj_database_url.config(
        default=f"postgresql://admin_conectades:conectaZ0Z6%40@{os.getenv('DB_HOST', 'db')}:5432/conectades",
        conn_max_age=600,
    )
}

# Redis Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://redis:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
                'socket_keepalive': True,
                'socket_keepalive_options': {},
            },
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
        }
    }
}

# Cache settings
CACHE_TTL = 3600  # 1 hora para dados estáveis
CACHE_TTL_SHORT = 300  # 5 minutos para dados dinâmicos
CACHE_TTL_USER = 1800  # 30 minutos para dados de usuário

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 3600  # 1 hora



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Exception handler customizado para sempre retornar JSON
    "EXCEPTION_HANDLER": "backend.core.exception_handler.custom_exception_handler",
    # Paginação padrão
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "PAGE_SIZE_QUERY_PARAM": "page_size",
    "MAX_PAGE_SIZE": 100,
    # Throttling para controlar requests
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/min",
        "user": "200/min",
    },
    # Renderers otimizados
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Conectades API",
    "DESCRIPTION": """
# API Conectades - Plataforma de Campanhas de Doação

## 🌐 CORS Configurado
Esta API possui CORS configurado para permitir requisições de:
- `http://localhost:3000` (React/Next.js)
- `http://localhost:5173` (Vite)
- `http://127.0.0.1:3000`
- `http://127.0.0.1:5173`

## 🔐 Autenticação
A API usa JWT (JSON Web Tokens) para autenticação.

### Como usar:
1. Faça login em `/api/auth/login/` para obter os tokens
2. Use o `access` token no header: `Authorization: Bearer <seu-token>`
3. Quando o `access` expirar (5 min), use o `refresh` token em `/api/token/refresh/`

## 📝 Cadastro com Link de Ativação
O fluxo de cadastro funciona em 2 etapas:
1. POST `/api/auth/registro/iniciar/` - Envia dados e recebe email com link
2. GET `/api/auth/registro/ativar/<token>/` - Usuário clica no link e ativa a conta

## 🔄 Formato de Erros
Todos os erros retornam JSON no formato:
```json
{
  "error": "Descrição do erro",
  "detail": "Detalhes técnicos (apenas em DEBUG)",
  "error_type": "TipoDoErro"
}
```

## 📍 Localizações
As localizações são hierárquicas:
- `cidades`: Lista de cidades disponíveis
- `bairros_por_cidade`: Bairros agrupados por cidade

Consulte `/api/auth/opcoes/` para ver a estrutura completa.

## 📚 Documentação Adicional
- Guia Frontend Cadastro: `/docs/GUIA_FRONTEND_CADASTRO.md`
- Guia Frontend Localizações: `/docs/GUIA_FRONTEND_LOCALIZACOES.md`
- Resumo para Frontend: `/docs/RESUMO_PARA_FRONTEND.md`
    """,
    "VERSION": "1.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    # Usar CDN para Swagger UI (resolve problema de static files)
    "SWAGGER_UI_DIST": "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0",
    "SWAGGER_UI_FAVICON_HREF": "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/favicon-32x32.png",
    "REDOC_DIST": "https://cdn.jsdelivr.net/npm/redoc@2.1.3",
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        "displayRequestDuration": True,
        "filter": True,
        "tryItOutEnabled": True,
    },
    "AUTHENTICATION_WHITELIST": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "COMPONENTS": {
        "securitySchemes": {
            "JWT": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "Token JWT obtido via login. Formato: `Bearer <seu-token>`"
            }
        }
    },
    "SECURITY": [
        {"JWT": []},
    ],
    "SERVERS": [
        {
            "url": "http://srv1037558.hstgr.cloud:8001",
            "description": "Servidor de Desenvolvimento (via Nginx)"
        },
        {
            "url": "http://localhost:8001",
            "description": "Desenvolvimento Local (via Nginx)"
        },
    ],
    "TAGS": [
        {"name": "Cadastro - Público", "description": "Endpoints de cadastro e ativação (sem autenticação)"},
        {"name": "Autenticação - Público", "description": "Login e recuperação de senha (sem autenticação)"},
        {"name": "Recuperação de Senha - Público", "description": "Fluxo de recuperação de senha"},
        {"name": "Perfil - Protegido", "description": "Gerenciamento de perfil do usuário (requer JWT)"},
        {"name": "Campanhas", "description": "Gerenciamento de campanhas de doação"},
        {"name": "Doações", "description": "Sistema de doações"},
    ],
}

AUTH_USER_MODEL = "pessoas.Pessoa"



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================
# ============================================================================
# CONFIGURAÇÃO DE EMAIL
# ============================================================================

# Escolher backend baseado na variável de ambiente
# Valores possíveis: 'console', 'smtp', 'file'
email_backend_type = os.getenv('EMAIL_BACKEND', 'console')

if email_backend_type == 'smtp':
    # Configuração SMTP (Gmail, SendGrid, Mailgun, etc.)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
    EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        import warnings
        warnings.warn(
            "⚠️  EMAIL_BACKEND está configurado como 'smtp', mas EMAIL_HOST_USER ou "
            "EMAIL_HOST_PASSWORD não foram definidos. Emails não serão enviados!",
            RuntimeWarning
        )
elif email_backend_type == 'file':
    # Salvar emails em arquivos (útil para desenvolvimento)
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    EMAIL_FILE_PATH = os.getenv('EMAIL_FILE_PATH', BASE_DIR / 'sent_emails')
else:
    # Console (padrão para desenvolvimento) - apenas imprime no log
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Configurações gerais de email
# Em SMTP, usar o mesmo email do HOST_USER para evitar rejeição
if email_backend_type == 'smtp' and EMAIL_HOST_USER:
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
else:
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@conectades.com')

SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8001')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# ============================================================================
# CONFIGURAÇÕES CORS (Cross-Origin Resource Sharing)
# ============================================================================

# Permitir requests de qualquer origem em desenvolvimento
# Em produção, especifique as origens permitidas
CORS_ALLOW_ALL_ORIGINS = DEBUG  # True em DEV, False em PROD

# Em produção, especifique as origens permitidas:
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5173',  # Vite default
    'http://localhost:8001',  # Nginx local
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:8001',
    'http://srv1037558.hstgr.cloud:8001',  # Servidor de desenvolvimento
    # Adicione aqui suas URLs de produção quando houver
]

# Permitir credenciais (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# ============================================================================
# CONFIGURAÇÕES CSRF (Cross-Site Request Forgery)
# ============================================================================

# Origens confiáveis para verificação CSRF (necessário para admin e formulários)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5173',
    'http://localhost:8001',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:8001',
    'http://srv1037558.hstgr.cloud:8001',
    # Adicione aqui suas URLs de produção quando houver (use https://)
]

# Permitir todos os métodos HTTP
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Permitir todos os headers necessários
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Expor headers para o frontend
CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]

# Cache de preflight requests (OPTIONS) por 1 hora
CORS_PREFLIGHT_MAX_AGE = 3600

# ============================================================================
# FIM CONFIGURAÇÕES CORS
# ============================================================================

# Configurações adicionais de email
EMAIL_TIMEOUT = 10  # segundos
EMAIL_USE_LOCALTIME = True
