# Generated by Django 5.2.5 on 2025-09-09 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alimento', 'Alimento'), ('roupa', 'Roupa'), ('brinquedo', 'Brinquedo'), ('servico', 'Serviço'), ('outro', 'Outro')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_doacao', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='campanhas.campanha')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
