# Generated by Django 5.2.5 on 2025-10-19 22:59

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
        ('pessoas', '0009_codigoverificacao'),
        ('campanhas', '0002_auto_20251019_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doacao',
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alimento', 'Alimento'), ('roupa', 'Roupa'), ('brinquedo', 'Brinquedo'), ('servico', 'Serviço'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], help_text='Tipo do que está sendo doado', max_length=50, verbose_name='Tipo de Doação')),
                ('titulo', models.CharField(help_text="Título da doação (ex: 'Doação de 5kg de arroz')", max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(help_text='Descrição detalhada do que está sendo doado', verbose_name='Descrição')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade do item/serviço sendo doado', verbose_name='Quantidade')),
                ('unidade', models.CharField(default='unidade', help_text='Unidade de medida (kg, litros, horas, etc.)', max_length=50, verbose_name='Unidade')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado da doação em reais (opcional)', max_digits=10, null=True, verbose_name='Valor Estimado')),
                ('data_doacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a doação foi registrada', verbose_name='Data da Doação')),
                ('data_entrega', models.DateTimeField(blank=True, help_text='Data prevista ou efetiva da entrega', null=True, verbose_name='Data de Entrega')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='pendente', help_text='Status atual da doação', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre a doação', null=True, verbose_name='Observações')),
                ('campanha', models.ForeignKey(help_text='Campanha para a qual esta doação é destinada', on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='campanhas.campanha', verbose_name='Campanha')),
                ('doador', models.ForeignKey(help_text='Pessoa que está fazendo a doação', on_delete=django.db.models.deletion.CASCADE, related_name='doacoes_feitas', to='pessoas.pessoa', verbose_name='Doador')),
                ('imagem', models.ForeignKey(blank=True, help_text='Imagem do item/serviço sendo doado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanhas.imagem', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-data_doacao'],
            },
        ),
    ]
