# Generated by Django 5.2.5 on 2025-10-19 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_auto_20251019_2257'),
        ('doacoes', '0002_auto_20251019_2259'),
        ('pessoas', '0009_codigoverificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoacaoIndependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Ex: 'Atendimento Odontológico Voluntário'", max_length=200, verbose_name='Título do Serviço')),
                ('descricao', models.TextField(help_text='Descrição detalhada do serviço oferecido', verbose_name='Descrição')),
                ('tipo_servico', models.CharField(choices=[('saude', 'Saúde'), ('juridico', 'Jurídico'), ('educacao', 'Educação'), ('tecnico', 'Técnico'), ('social', 'Social'), ('outro', 'Outro')], help_text='Categoria do serviço oferecido', max_length=50, verbose_name='Tipo de Serviço')),
                ('quantidade_pessoas', models.PositiveIntegerField(help_text='Quantas pessoas podem ser atendidas por vez', verbose_name='Quantidade de Pessoas')),
                ('duracao_atendimento', models.PositiveIntegerField(help_text='Tempo médio de cada atendimento em minutos', verbose_name='Duração do Atendimento (minutos)')),
                ('frequencia_semanal', models.PositiveIntegerField(default=1, help_text='Quantas vezes por semana o serviço é oferecido', verbose_name='Frequência Semanal')),
                ('data_inicio', models.DateTimeField(help_text='Quando o serviço começará a ser oferecido', verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, help_text='Quando o serviço terminará (opcional)', null=True, verbose_name='Data de Fim')),
                ('dias_semana', models.JSONField(default=list, help_text='Dias da semana em que o serviço está disponível (0=Segunda, 6=Domingo)', verbose_name='Dias da Semana')),
                ('horario_inicio', models.TimeField(help_text='Horário que o atendimento começa', verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(help_text='Horário que o atendimento termina', verbose_name='Horário de Fim')),
                ('endereco_detalhado', models.TextField(blank=True, help_text='Endereço específico ou instruções de localização', null=True, verbose_name='Endereço Detalhado')),
                ('whatsapp', models.CharField(help_text='Número para contato direto', max_length=20, verbose_name='WhatsApp')),
                ('email_contato', models.EmailField(blank=True, help_text='Email para contato (opcional)', max_length=254, null=True, verbose_name='Email de Contato')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='ativa', help_text='Status atual da doação independente', max_length=20, verbose_name='Status')),
                ('ativa', models.BooleanField(default=True, help_text='Se a doação está ativa para receber solicitações', verbose_name='Ativa')),
                ('requisitos', models.TextField(blank=True, help_text='Requisitos para quem quer ser atendido', null=True, verbose_name='Requisitos')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o serviço', null=True, verbose_name='Observações')),
                ('agendamentos_confirmados', models.PositiveIntegerField(default=0, help_text='Quantidade de agendamentos confirmados', verbose_name='Agendamentos Confirmados')),
                ('agendamentos_realizados', models.PositiveIntegerField(default=0, help_text='Quantidade de agendamentos já realizados', verbose_name='Agendamentos Realizados')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('categorias', models.ManyToManyField(help_text='Categorias relacionadas ao serviço', to='pessoas.categoriainteresse', verbose_name='Categorias')),
                ('doadora', models.ForeignKey(help_text='Pessoa que está oferecendo o serviço', on_delete=django.db.models.deletion.CASCADE, related_name='doacoes_independentes', to=settings.AUTH_USER_MODEL, verbose_name='Doadora')),
                ('imagem', models.ForeignKey(blank=True, help_text='Imagem representativa do serviço', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanhas.imagem', verbose_name='Imagem')),
                ('localizacao', models.ForeignKey(blank=True, help_text='Onde o serviço será prestado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.localizacaointeresse', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Doação Independente',
                'verbose_name_plural': 'Doações Independentes',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
