# Generated by Django 5.2.5 on 2025-10-19 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0003_doacaoindependente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do tipo de doação (ex: Alimento, Roupa, Serviço)', max_length=100, unique=True, verbose_name='Nome')),
                ('codigo', models.CharField(help_text='Código único para identificação (ex: alimento, roupa, servico)', max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do tipo de doação', null=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone (ex: fas fa-heart, fas fa-tshirt)', max_length=50, null=True, verbose_name='Ícone')),
                ('cor', models.CharField(default='#007bff', help_text='Cor em hexadecimal (ex: #007bff)', max_length=7, verbose_name='Cor')),
                ('ativo', models.BooleanField(default=True, help_text='Se este tipo está disponível para seleção', verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor número aparece primeiro)', verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tipo de Doação',
                'verbose_name_plural': 'Tipos de Doação',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do tipo de serviço (ex: Saúde, Jurídico, Educação)', max_length=100, unique=True, verbose_name='Nome')),
                ('codigo', models.CharField(help_text='Código único para identificação (ex: saude, juridico, educacao)', max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do tipo de serviço', null=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone (ex: fas fa-stethoscope, fas fa-gavel)', max_length=50, null=True, verbose_name='Ícone')),
                ('cor', models.CharField(default='#28a745', help_text='Cor em hexadecimal (ex: #28a745)', max_length=7, verbose_name='Cor')),
                ('ativo', models.BooleanField(default=True, help_text='Se este tipo está disponível para seleção', verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor número aparece primeiro)', verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='doacao',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo do que está sendo doado', on_delete=django.db.models.deletion.PROTECT, to='doacoes.tipodoacao', verbose_name='Tipo de Doação'),
        ),
        migrations.AlterField(
            model_name='doacaoindependente',
            name='tipo_servico',
            field=models.ForeignKey(help_text='Categoria do serviço oferecido', on_delete=django.db.models.deletion.PROTECT, to='doacoes.tiposervico', verbose_name='Tipo de Serviço'),
        ),
    ]
