# Generated by Django 5.2.5 on 2025-10-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0004_tipodoacao_tiposervico_alter_doacao_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='valor_estimado',
        ),
    ]
