# Generated by Django 5.2.5 on 2025-10-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0007_remove_titulo_descricao_from_doacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='tipo',
        ),
    ]
