# Generated by Django 5.2.5 on 2025-10-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0008_remove_doacao_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoDoacao',
        ),
    ]
