# Generated by Django 5.2.5 on 2025-09-09 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_organizadora', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('beneficiaria', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'beneficiaria'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanhas_beneficiaria', to=settings.AUTH_USER_MODEL)),
                ('organizadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='campanhas.organizadora')),
            ],
        ),
    ]
