# Generated by Django 5.2.5 on 2025-10-19 22:57

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
        ('pessoas', '0009_codigoverificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(help_text='Arquivo da imagem baseado no tipo de arquivo', upload_to='campanhas/imagens/', verbose_name='Arquivo da Imagem')),
                ('alt', models.CharField(help_text='Texto alternativo para acessibilidade', max_length=200, verbose_name='Texto Alternativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do item solicitado', max_length=200, verbose_name='Nome do Item')),
                ('quantidade_solicitada', models.PositiveIntegerField(help_text='Quantidade total solicitada do item', verbose_name='Quantidade Solicitada')),
                ('quantidade_contribuida', models.PositiveIntegerField(default=0, help_text='Quantidade já contribuída do item', verbose_name='Quantidade Contribuída')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do usuário externo', max_length=100, verbose_name='Nome')),
                ('cidade', models.CharField(help_text='Cidade do usuário externo', max_length=100, verbose_name='Cidade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('bairro', models.ForeignKey(blank=True, help_text='Bairro do usuário externo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.localizacaointeresse', verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Usuário Externo',
                'verbose_name_plural': 'Usuários Externos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(help_text='Quantidade contribuída', verbose_name='Quantidade')),
                ('mensagem', models.TextField(blank=True, help_text='Mensagem opcional do contribuidor', null=True, verbose_name='Mensagem')),
                ('data_contribuicao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Contribuição')),
                ('item', models.ForeignKey(help_text='Item contribuído', on_delete=django.db.models.deletion.CASCADE, to='campanhas.item', verbose_name='Item')),
                ('usuario', models.ForeignKey(help_text='Usuário que fez a contribuição', on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Contribuição',
                'verbose_name_plural': 'Contribuições',
                'ordering': ['-data_contribuicao'],
            },
        ),
        migrations.CreateModel(
            name='PostAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(help_text='Conteúdo da atualização', verbose_name='Mensagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('imagem', models.ForeignKey(blank=True, help_text='Imagem opcional da atualização', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanhas.imagem', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Post de Atualização',
                'verbose_name_plural': 'Posts de Atualização',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='Campanha',
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da campanha', max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(default='', help_text='Subtítulo da campanha', max_length=300, verbose_name='Subtítulo')),
                ('descricao', models.TextField(help_text='Descrição detalhada da campanha', verbose_name='Descrição')),
                ('whatsapp', models.CharField(default='', help_text='Número do WhatsApp para contato', max_length=20, verbose_name='WhatsApp')),
                ('data_inicio', models.DateTimeField(default=timezone.now, help_text='Data e hora de início da campanha', verbose_name='Data de Início')),
                ('prazo', models.DateTimeField(default=timezone.now, help_text='Data e hora limite da campanha', verbose_name='Prazo')),
                ('ativa', models.BooleanField(default=True, help_text='Se a campanha está ativa', verbose_name='Ativa')),
                ('atualizacoes', models.ManyToManyField(help_text='Posts de atualização da campanha', to='campanhas.postatualizacao', verbose_name='Atualizações')),
                ('categorias', models.ManyToManyField(help_text='Categorias relacionadas à campanha', to='pessoas.categoriainteresse', verbose_name='Categorias')),
                ('contribuicoes', models.ManyToManyField(help_text='Contribuições recebidas', to='campanhas.contribuicao', verbose_name='Contribuições')),
                ('imagem', models.ForeignKey(blank=True, help_text='Imagem principal da campanha', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanhas.imagem', verbose_name='Imagem')),
                ('localizacao', models.ForeignKey(blank=True, help_text='Localização da campanha', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.localizacaointeresse', verbose_name='Localização')),
                ('organizadora', models.ForeignKey(help_text='Organizadora é a usuária que criou a campanha', on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='campanhas.organizadora', verbose_name='Organizadora')),
                ('solicitacoes', models.ManyToManyField(help_text='Itens solicitados na campanha', to='campanhas.item', verbose_name='Solicitações')),
                ('usuario_externo', models.ForeignKey(blank=True, help_text='Usuário externo relacionado à campanha', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanhas.usuarioexterno', verbose_name='Usuário Externo')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
