# Generated by Django 5.2.5 on 2025-10-20 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0005_rename_item_to_itemcampanha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='beneficiaria',
            field=models.ForeignKey(blank=True, help_text='Pessoa beneficiária desta campanha (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_como_beneficiaria', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiária'),
        ),
    ]
