# Generated by Django 5.2.5 on 2025-10-20 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0007_add_campanha_to_postatualizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='beneficiaria_confirmada',
            field=models.BooleanField(default=False, help_text='Se a beneficiária aceitou ser associada a esta campanha', verbose_name='Beneficiária Confirmada'),
        ),
        migrations.CreateModel(
            name='SolicitacaoBeneficiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='pendente', help_text='Status da solicitação', max_length=20, verbose_name='Status')),
                ('mensagem_organizadora', models.TextField(blank=True, default='', help_text='Mensagem da organizadora explicando por que a beneficiária foi escolhida', verbose_name='Mensagem da Organizadora')),
                ('mensagem_resposta', models.TextField(blank=True, default='', help_text='Mensagem da beneficiária ao aceitar ou recusar', verbose_name='Mensagem de Resposta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_resposta', models.DateTimeField(blank=True, help_text='Data em que a beneficiária respondeu à solicitação', null=True, verbose_name='Data de Resposta')),
                ('beneficiaria', models.ForeignKey(help_text='Pessoa que foi indicada como beneficiária', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_campanha', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiária')),
                ('campanha', models.ForeignKey(help_text='Campanha para a qual a beneficiária foi indicada', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_beneficiaria', to='campanhas.campanha', verbose_name='Campanha')),
                ('organizadora', models.ForeignKey(help_text='Organizadora que criou a solicitação', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_enviadas', to='campanhas.organizadora', verbose_name='Organizadora')),
            ],
            options={
                'verbose_name': 'Solicitação de Beneficiária',
                'verbose_name_plural': 'Solicitações de Beneficiária',
                'ordering': ['-data_criacao'],
                'unique_together': {('campanha', 'beneficiaria')},
            },
        ),
    ]
