# Generated by Django 5.2.5 on 2025-10-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0008_campanha_beneficiaria_confirmada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='publicada',
            field=models.BooleanField(default=False, help_text='Se a campanha foi publicada e está visível para doadores. Só pode ser True se beneficiária confirmar OU se não houver beneficiária.', verbose_name='Publicada'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Se a campanha está ativa e visível publicamente', verbose_name='Ativa'),
        ),
    ]
