# Generated by Django 5.2.7 on 2025-10-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nome_alias',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Sua foto de perfil', null=True, upload_to='avatars/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='categorias_interesse',
            field=models.JSONField(blank=True, default=list, help_text='Áreas que você tem interesse', verbose_name='Categorias de Interesse'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(choices=[('mulher_cis', 'Mulher Cis'), ('mulher_trans', 'Mulher Trans'), ('travesti', 'Travesti'), ('homem_cis', 'Homem Cis'), ('homem_trans', 'Homem Trans'), ('nao_binario', 'Não-binário'), ('agenero', 'Agênero'), ('genero_fluido', 'Gênero Fluido'), ('outro', 'Outro'), ('prefiro_nao_informar', 'Prefiro não informar')], default='prefiro_nao_informar', help_text='Como você se identifica', max_length=30, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='localizacoes_interesse',
            field=models.JSONField(blank=True, default=list, help_text='Bairros/cidades de interesse', verbose_name='Localizações de Interesse'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_completo',
            field=models.CharField(default='', help_text='Nome completo da pessoa', max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_social',
            field=models.CharField(blank=True, help_text='Nome que você gostaria de ser chamada', max_length=50, null=True, verbose_name='Nome Social'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo_usuario',
            field=models.CharField(choices=[('beneficiaria', 'Beneficiária'), ('doadora', 'Doadora'), ('organizadora', 'Organizadora')], default='doadora', help_text='Selecione seu tipo de usuário', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(default='', help_text='Bairro onde você mora', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(default='', help_text='Cidade onde você mora', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='', help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='', help_text='E-mail para contato', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mini_bio',
            field=models.TextField(blank=True, help_text='Conte um pouco sobre você (opcional)', max_length=500, null=True, verbose_name='Mini Biografia'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(default='', help_text='Número de telefone com DDD', max_length=20, verbose_name='Telefone'),
        ),
    ]
