# Generated by Django 5.2.7 on 2025-10-15 02:18

from django.db import migrations, models
import django.db.models.deletion


def populate_required_fields(apps, schema_editor):
    """Popula campos obrigatórios com valores padrão para registros existentes"""
    Pessoa = apps.get_model('pessoas', 'Pessoa')
    
    for pessoa in Pessoa.objects.all():
        # Preenche campos obrigatórios com valores padrão se estiverem vazios
        if not pessoa.nome_social:
            pessoa.nome_social = pessoa.nome_completo or pessoa.username
        if not pessoa.mini_bio:
            pessoa.mini_bio = "Perfil criado automaticamente"
        if not pessoa.categorias_interesse:
            pessoa.categorias_interesse = ["outros"]
        if not pessoa.localizacoes_interesse:
            pessoa.localizacoes_interesse = [{"id": pessoa.bairro or pessoa.cidade, "label": pessoa.bairro or pessoa.cidade}]
        pessoa.save()


def reverse_populate_required_fields(apps, schema_editor):
    """Reverte as mudanças (não faz nada específico)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_pessoa_options_remove_pessoa_endereco_and_more'),
    ]

    operations = [
        # Primeiro, popula os campos obrigatórios
        migrations.RunPython(populate_required_fields, reverse_populate_required_fields),
        
        # Depois, torna os campos não-nullable
        migrations.AlterField(
            model_name='pessoa',
            name='avatar',
            field=models.ImageField(help_text='Sua foto de perfil', upload_to='avatars/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='categorias_interesse',
            field=models.JSONField(help_text='Áreas que você tem interesse', verbose_name='Categorias de Interesse'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='localizacoes_interesse',
            field=models.JSONField(help_text='Bairros/cidades de interesse', verbose_name='Localizações de Interesse'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mini_bio',
            field=models.TextField(help_text='Conte um pouco sobre você', max_length=500, verbose_name='Mini Biografia'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_social',
            field=models.CharField(help_text='Nome que você gostaria de ser chamada', max_length=50, verbose_name='Nome Social'),
        ),
    ]
