# Generated by Django 5.2.7 on 2025-10-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_auto_20251015_0226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localizacaointeresse',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='categoriainteresse',
            name='codigo',
            field=models.CharField(editable=False, help_text='Código único gerado automaticamente da categoria', max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='categoriainteresse',
            name='nome',
            field=models.CharField(help_text='Nome exibido da categoria (ex: Alimentação, Vestuário)', max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='codigo',
            field=models.CharField(editable=False, help_text='Código único gerado automaticamente do gênero', max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(help_text='Nome exibido do gênero (ex: Mulher Cis, Não-binário)', max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='localizacaointeresse',
            name='codigo',
            field=models.CharField(editable=False, help_text='Código único gerado automaticamente da localização', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='codigo',
            field=models.CharField(editable=False, help_text='Código único gerado automaticamente do tipo', max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='nome',
            field=models.CharField(help_text='Nome exibido do tipo (ex: Doadora, Beneficiária)', max_length=50, unique=True, verbose_name='Nome'),
        ),
    ]
