# Generated by Django 5.2.7 on 2025-10-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_alter_localizacaointeresse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacaointeresse',
            name='codigo',
            field=models.CharField(editable=False, help_text='Código único gerado automaticamente da localização', max_length=100, unique=True, verbose_name='Código'),
        ),
    ]
