# Generated by Django 5.2.7 on 2025-10-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_alter_localizacaointeresse_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriainteresse',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='categoriainteresse',
            name='icone',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
