# Generated by Django 5.2.7 on 2025-10-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_remove_categoriainteresse_cor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email para o qual o código foi enviado', max_length=254, verbose_name='Email')),
                ('codigo', models.CharField(help_text='Código de 6 dígitos gerado aleatoriamente', max_length=6, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('cadastro', 'Cadastro'), ('login', 'Login'), ('recuperacao', 'Recuperação de Senha')], default='cadastro', help_text='Finalidade do código', max_length=20, verbose_name='Tipo')),
                ('usado', models.BooleanField(default=False, help_text='Se o código já foi utilizado', verbose_name='Usado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_expiracao', models.DateTimeField(help_text='Código expira após 10 minutos', verbose_name='Data de Expiração')),
                ('tentativas', models.PositiveIntegerField(default=0, help_text='Número de tentativas de verificação', verbose_name='Tentativas')),
            ],
            options={
                'verbose_name': 'Código de Verificação',
                'verbose_name_plural': 'Códigos de Verificação',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['email', 'codigo', 'usado'], name='pessoas_cod_email_3cf71e_idx'), models.Index(fields=['data_expiracao'], name='pessoas_cod_data_ex_61849c_idx')],
            },
        ),
    ]
