# Generated by Django 5.2.5 on 2025-10-30 00:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_codigoverificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoverificacao',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Token único para ativação via link', null=True, verbose_name='Token'),
        ),
        migrations.AddIndex(
            model_name='codigoverificacao',
            index=models.Index(fields=['token', 'usado'], name='pessoas_cod_token_df6d5c_idx'),
        ),
    ]
